services:
  frontend:
    build:
      context: ./dochadzka_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./dochadzka_backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:Tomik7727@49.13.194.189:5432/dochadzka
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  pgdata: